---
galaxy_info:
  author: 'Christophe Lacombe'
  description: 'Trellix ENS Firewall'
  company: 'Lacrif'
  license: 'GPL-2.0-or-later'
  min_ansible_version: '2.7'
  galaxy_tags:
    - 'trellix'
    - 'ens'

dependencies: []
